---
title: "software_cite_astropy"
author: "Daina Bouquin"
---

```{r}
library(dplyr)
library(plyr)
library(reshape2)

astropy <- read.csv("AstroPy_Mentions.csv")
```
Remove false positives
```{r}
valid_years <- c(2013:2018)
astropy <- filter(astropy, Publication_year %in% valid_years)
```

XML tag analysis
```{r}
# how many unique XML tags were used?
length(unique(astropy$XML_tag2)) # 9

# what were the tags?
unique(astropy$XML_tag2)

# ack 
# app 
# disp-formula 
# element-citation 
# list-item 
# nlm-citation 
# p 
# sec 
# td

# how many files contained aliases?
total_astropy_files <- length(unique(astropy$File_name))  # 497
total_astropy_files

# select only files where the tag shows an attempt to cite/acknowledge (astropy_attempt_ref)
ref <- c("source", "nlm-citation", "element-citation", "ack")
astropy_attempt_ref <- filter(astropy, XML_tag2 %in% ref)

# save astropy_attempt_ref
write.csv(astropy_attempt_ref, "astropy_attempt_ref.csv")

# how many files contained attempt to cite/acknowledge
cite_attempt_astropy <- length(unique(astropy_attempt_ref$File_name)) # 469
cite_attempt_astropy

# proportion of astropy mentions with an attempt at citation
cite_attempt_astropy / total_astropy_files # 0.943662

# select only files where the tag shows an attempt to formally cite the software (astropy_ref)
ref2 <- c("source", "nlm-citation", "element-citation")
astropy_ref <- filter(astropy, XML_tag2 %in% ref2)
write.csv(astropy_ref, "astropy_ref.csv")

# how many files contained a formal citation
formal_cite_astropy <- length(unique(astropy_ref$File_name)) # 455
formal_cite_astropy

# proportion of astropy mentions with a formal citation
formal_cite_astropy / total_astropy_files # 0.915493

# how many formal citations contained an "identifier"
ID_only <- filter(astropy, ID == 1)
ID_count <- length(unique(ID_only$File_name))
ID_count # 457

# proportion of astropy formal citations containing an identifier
ID_count / total_astropy_files # 0.9195171

# how many unique aliases were used in whole corpus
alias_count <- length(unique(astropy$Alias)) # 7
alias_count

# which aliases were used
aliases_used <- unique(astropy$Alias)
aliases_used

# 10.1051/0004-6361/201322068
# 2013A&A...558A..33A
# astropy
# AstroPy
# http://www.astropy.org/
# https://doi.org/10.1051/0004-6361/201322068
# https://github.com/astropy

# how often was each alias used
count(astropy, c('Alias'))

#                                       Alias freq
#                 10.1051/0004-6361/201322068  449
#                         2013A&A...558A..33A  441
#                                     astropy  229
#                                     AstroPy   31
#                     http://www.astropy.org/   11
# https://doi.org/10.1051/0004-6361/201322068    2
#                  https://github.com/astropy    8

# create subset of files not containing formal reference (astropy_no_ref)
astropy_no_ref <- filter(astropy, !File_name %in% astropy_ref$File_name)
no_ref <- length(unique(astropy_no_ref$File_name)) 
no_ref

write.csv(astropy_no_ref, "astropy_no_ref.csv")
```
