---
title: "software_cite_TARDIS"
author: "Daina Bouquin"
---

```{r}
library(dplyr)
library(plyr)
library(reshape2)

TARDIS <- read.csv("TARDIS_Mentions.csv")
```

XML tag analysis
```{r}
# how many unique XML tags were used?
length(unique(TARDIS$XML_tag2)) # 6

# what were the tags?
unique(TARDIS$XML_tag2)

# ack 
# aff 
# caption 
# oasis:row 
# p 
# sec

# how many files contained aliases?
total_TARDIS_files <- length(unique(TARDIS$File_name))  # 14
total_TARDIS_files

# select only files where the tag shows an attempt to cite/acknowledge (TARDIS_attempt_ref)
ref <- c("source", "nlm-citation", "element-citation", "ack")
TARDIS_attempt_ref <- filter(TARDIS, XML_tag2 %in% ref)

# save TARDIS_attempt_ref
write.csv(TARDIS_attempt_ref, "TARDIS_attempt_ref.csv")

# how many files contained attempt to cite/acknowledge
cite_attempt_TARDIS <- length(unique(TARDIS_attempt_ref$File_name)) # 1
cite_attempt_TARDIS

# proportion of TARDIS mentions with an attempt at citation
cite_attempt_TARDIS / total_TARDIS_files # 0.07142857

# select only files where the tag shows an attempt to formally cite the software (TARDIS_ref)
ref2 <- c("source", "nlm-citation", "element-citation")
TARDIS_ref <- filter(TARDIS, XML_tag2 %in% ref2)
write.csv(TARDIS_ref, "TARDIS_ref.csv")

# how many files contained a formal citation
formal_cite_TARDIS <- length(unique(TARDIS_ref$File_name)) # 0
formal_cite_TARDIS

# proportion of TARDIS mentions with a formal citation
formal_cite_TARDIS / total_TARDIS_files # 0

# how many formal citations contained an "identifier"
ID_only <- filter(TARDIS, ID == 1)
ID_count <- length(unique(ID_only$File_name))
ID_count # 0

# proportion of TARDIS formal citations containing an identifier
ID_count / total_TARDIS_files # 0

# how many unique aliases were used in whole corpus
alias_count <- length(unique(TARDIS$Alias)) # 3
alias_count

# which aliases were used
aliases_used <- unique(TARDIS$Alias)
aliases_used

# tardis 
# TARDIS 
# Tardis

# how often was each alias used
count(TARDIS, c('Alias'))

#   Alias freq
# tardis   15
# Tardis   17
# TARDIS   11

# create subset of files not containing formal reference (TARDIS_no_ref)
TARDIS_no_ref <- filter(TARDIS, !File_name %in% TARDIS_ref$File_name)
no_ref <- length(unique(TARDIS_no_ref$File_name)) 
no_ref

write.csv(TARDIS_no_ref, "TARDIS_no_ref.csv")
```