---
title: "software_cite_SAOImageDS9"
author: "Daina Bouquin"
---

```{r}
library(dplyr)
library(plyr)
library(reshape2)

SAOImageDS9 <- read.csv("SAOImageDS9__Mentions.csv")
```
Remove false positives
```{r}
valid_years <- c(2002:2018)
SAOImageDS9 <- filter(SAOImageDS9, Publication_year %in% valid_years)

# remove confounds
confounds <- c("CDS91","CDS92","DS91","DS92","DS93","DS94","DS95","DS96","DS97","DS98","DS96Â","MDS94","MDS95","MDS96","FDS99","BDS90","GDS99","ADS94","SDS99","RDS94","UDS9","UDS910-0","UDS910-1","UDS910-3","UDS910-4","ODS95")

SAOImageDS9 <- filter(SAOImageDS9, !XML_tag1_content %in% confounds)
```

XML tag analysis
```{r}
# how many unique XML tags were used?
length(unique(SAOImageDS9$XML_tag2)) # 14

# what were the tags?
unique(SAOImageDS9$XML_tag2)

# element-citation 
# nlm-citation     
# sec              
# ref              
# p                
# fn               
# ack              
# caption
# tr               
# table-wrap-foot  
# app              
# oasis:row        
# list-item        
# disp-formula  

# how many files contained aliases?
total_SAOImageDS9_files <- length(unique(SAOImageDS9$File_name))  # 463
total_SAOImageDS9_files

# select only files where the tag shows an attempt to cite/acknowledge (SAOImageDS9_attempt_ref)
ref <- c("source", "nlm-citation", "element-citation", "ack")
SAOImageDS9_attempt_ref <- filter(SAOImageDS9, XML_tag2 %in% ref)

# save SAOImageDS9_attempt_ref
write.csv(SAOImageDS9_attempt_ref, "SAOImageDS9_attempt_ref.csv")

# how many files contained attempt to cite/acknowledge
cite_attempt_SAOImageDS9 <- length(unique(SAOImageDS9_attempt_ref$File_name)) # 169
cite_attempt_SAOImageDS9

# proportion of SAOImageDS9 mentions with an attempt at citation
cite_attempt_SAOImageDS9 / total_SAOImageDS9_files # 0.3650108

# select only files where the tag shows an attempt to formally cite the software (SAOImageDS9_ref)
ref2 <- c("source", "nlm-citation", "element-citation")
SAOImageDS9_ref <- filter(SAOImageDS9, XML_tag2 %in% ref2)
write.csv(SAOImageDS9_ref, "SAOImageDS9_ref.csv")

# how many files contained a formal citation
formal_cite_SAOImageDS9 <- length(unique(SAOImageDS9_ref$File_name)) # 60
formal_cite_SAOImageDS9

# proportion of SAOImageDS9 mentions with a formal citation
formal_cite_SAOImageDS9 / total_SAOImageDS9_files # 0.1295896

# how many formal citations contained an "identifier"
ID_only <- filter(SAOImageDS9, ID == 1)
ID_count <- length(unique(ID_only$File_name))
ID_count # 57

# proportion of SAOImageDS9 formal citations containing an identifier
ID_count / total_SAOImageDS9_files # 0.1231102

# how many unique aliases were used in whole corpus
alias_count <- length(unique(SAOImageDS9$Alias)) # 9
alias_count

# which aliases were used
aliases_used <- unique(SAOImageDS9$Alias)
aliases_used

# 2000ascl.soft03002S
# 2003ASPC..295..489J
# DS9
# ds9
# http://deep.ps.uci.edu/spec2d/
# http://ds9.si.edu
# SAOImage
# saoimage
# SAOImage DS9

# how often was each alias used
count(SAOImageDS9, c('Alias'))

#                          Alias freq
#            2000ascl.soft03002S    1
#            2003ASPC..295..489J   56
#                            ds9  178
#                            DS9  408
# http://deep.ps.uci.edu/spec2d/    2
#              http://ds9.si.edu   22
#                       saoimage    2
#                       SAOImage   24
#                   SAOImage DS9  199  

# create subset of files not containing formal reference (SAOImageDS9_no_ref)
SAOImageDS9_no_ref <- filter(SAOImageDS9, !File_name %in% SAOImageDS9_ref$File_name)
no_ref <- length(unique(SAOImageDS9_no_ref$File_name)) 
no_ref

write.csv(SAOImageDS9_no_ref, "SAOImageDS9_no_ref.csv")
```